#include <verilated.h>
#include <verilated_vcd_c.h> // Required for waveform tracing
#include "Vtop.h"      // The header generated by Verilator

// Global pointers for the simulation state
Vtop* top = nullptr;
VerilatedVcdC* tfp = nullptr;
uint32_t global_data_width = 0;

// Simulation time counter
vluint64_t main_time = 0;

// Called by $time in Verilog (Verilator requires this function to be defined)
double sc_time_stamp() {
    return main_time;
}

extern "C" {

    // 1. Initialization
    void sim_init(const char* vcd_filename) {

        // Context setup
        VerilatedContext* contextp = Verilated::threadContextp();
        contextp->timeunit(-11);
        contextp->timeprecision(-11);

        // Instantiate the module
        top = new Vtop;

        // Enable VCD tracing if a filename was provided
        if (vcd_filename) {
            Verilated::traceEverOn(true);
            tfp = new VerilatedVcdC;
            top->trace(tfp, 99);
            tfp->open(vcd_filename);
        }
    }

    // 2. Cleanup
    void sim_cleanup() {
        // Run any final Verilog blocks
        top->final();

        // Safely close and delete the trace file
        if (tfp) {
            tfp->close();
            delete tfp;
            tfp = nullptr;
        }

        // Delete the module
        delete top;
        top = nullptr;
    }

    // 3. Clock Tick (Simulates half a clock cycle)
    void sim_tick() {
        // Toggle the clock (Assumes your clock port is named 'clk')
        top->clk = top->clk ? 0 : 1;

        // Evaluate the combinatorial logic
        top->eval();

        // Dump the trace data to the VCD file for this specific time step
        if (tfp) {
            tfp->dump(main_time);
        }

        // Advance simulation time
        main_time++;
    }

    // ---------------------------------------------------------
    // 4. Port Accessors (CUSTOMIZE THESE FOR YOUR VERILOG CODE)
    // ---------------------------------------------------------

    void sim_set_reset(int val) {
        // Assumes your Verilog has a port named 'reset'
        top->rst = val;
    }

    void sim_set_data(int val) {
        // Assumes your Verilog has an input port named 'data_in'
        top->t_0_dat = val;
    }

    int sim_get_result() {
        // Assumes your Verilog has an output port named 'data_out'
        return top->i_0_dat;
    }

    double get_time_stamp() {
        return main_time;
    }
}